2022-07-24 10:24:23,355 - ERROR - main - Enter into the new_function()
2022-07-24 10:24:23,361 - WARNING - main - Enter into the main()
2022-07-24 10:24:44,252 - WARNING - main - Enter into the main()
2022-07-24 10:25:20,836 - WARNING - main - Enter into the new_function()
2022-07-24 10:25:20,837 - WARNING - main - Enter into the main()
2022-07-24 10:26:15,462 - ERROR - main - Enter into the new_function()
2022-07-24 10:26:15,467 - WARNING - main - Enter into the main()
2022-07-24 10:28:20,304 - ERROR - main - Enter into the new_function()
2022-07-24 10:28:20,305 - WARNING - main - Enter into the main()
2022-07-24 10:34:23,438 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:34:23,443 - WARNING - main - Enter into the main()
2022-07-24 10:34:32,456 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:34:32,461 - WARNING - main - Enter into the main()
2022-07-24 10:34:52,664 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:34:52,670 - WARNING - main - Enter into the main()
2022-07-24 10:34:58,533 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:34:58,537 - WARNING - main - Enter into the main()
2022-07-24 10:35:38,368 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:36:13,075 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:36:21,914 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:37:37,572 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:37:37,573 - ERROR - main - Enter into the main()
2022-07-24 10:41:01,526 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:41:01,527 - ERROR - main - Enter into the main()
2022-07-24 10:41:01,528 - ERROR - main - Exception here
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 62, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 10:42:00,888 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:42:00,889 - ERROR - main - Enter into the main()
2022-07-24 10:44:43,030 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:44:43,031 - ERROR - main - Enter into the main()
2022-07-24 10:51:09,573 - ERROR - main - Enter into the new_function()
NoneType: None
2022-07-24 10:51:09,575 - ERROR - main - Enter into the main()
2022-07-24 10:51:09,576 - INFO - main - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 62, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 10:52:17,316 - CRITICAL - main - Enter into the new_function()
NoneType: None
2022-07-24 10:52:17,318 - ERROR - main - Enter into the main()
2022-07-24 10:52:17,319 - CRITICAL - main - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 62, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 10:53:02,598 - CRITICAL - main - Enter into the new_function()
NoneType: None
2022-07-24 10:53:02,600 - CRITICAL - main - Enter into the main()
2022-07-24 10:53:02,601 - INFO - main - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 62, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 10:53:20,547 - CRITICAL - main - Enter into the new_function()
NoneType: None
2022-07-24 10:53:20,549 - CRITICAL - main - Enter into the main()
2022-07-24 11:49:49,526 - CRITICAL - main - Check - logger "django" - Enter into the new_function()
NoneType: None
2022-07-24 11:51:14,064 - CRITICAL - main - Check - logger "django" - Enter into the new_function()
NoneType: None
2022-07-24 11:51:14,065 - CRITICAL - main - Check - logger "django" - Enter into the main()
2022-07-24 11:51:14,066 - CRITICAL - main - Check - logger "django" - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 74, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 11:51:48,157 - ERROR - main - Check - logger "django" - Enter into the new_function()
NoneType: None
2022-07-24 11:51:48,158 - ERROR - main - Check - logger "django" - Enter into the main()
2022-07-24 11:51:48,159 - ERROR - main - Check - logger "django" - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 74, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 11:52:27,906 - WARNING - main - Check - logger "django" - Enter into the new_function()
NoneType: None
2022-07-24 11:52:27,906 - WARNING - main - Check - logger "django" - Enter into the main()
2022-07-24 11:52:27,907 - WARNING - main - Check - logger "django" - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 74, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 11:53:01,716 - INFO - main - Check - logger "django" - Enter into the new_function()
NoneType: None
2022-07-24 11:53:01,717 - INFO - main - Check - logger "django" - Enter into the main()
2022-07-24 11:53:01,717 - INFO - main - Check - logger "django" - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 74, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 12:08:29,967 - INFO - main - Check - logger.info - Enter into the new_function()
NoneType: None
2022-07-24 12:08:29,967 - INFO - main - Check - logger.info - Enter into the main()
2022-07-24 12:08:29,968 - INFO - main - Check - logger.info - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 75, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 12:09:51,598 - INFO - main - Check - logger.info - Enter into the new_function()
NoneType: None
2022-07-24 12:09:51,599 - INFO - main - Check - logger.info - Enter into the main()
2022-07-24 12:09:51,599 - INFO - main - Check - logger.info - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 75, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 12:10:13,475 - INFO - main - Check - logger.info - Enter into the new_function()
NoneType: None
2022-07-24 12:10:13,475 - INFO - main - Check - logger.info - Enter into the main()
2022-07-24 12:10:13,476 - INFO - main - Check - logger.info - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 75, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 16:35:02,025 - CRITICAL - main - CustomHandler test through "django" logger - Enter into the new_function()
NoneType: None
2022-07-24 16:35:02,026 - CRITICAL - main - CustomHandler test through "django" logger - Enter into the main()
2022-07-24 16:35:02,028 - CRITICAL - main - CustomHandler test through "django" logger - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 77, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 16:37:38,323 - ERROR - main - CustomHandler test through "django" logger - Enter into the new_function()
NoneType: None
2022-07-24 16:37:38,325 - ERROR - main - CustomHandler test through "django" logger - Enter into the main()
2022-07-24 16:37:38,326 - ERROR - main - CustomHandler test through "django" logger - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 77, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 16:38:23,148 - ERROR - main - CustomHandler test through "django" logger - Enter into the new_function()
NoneType: None
2022-07-24 16:38:23,150 - ERROR - main - CustomHandler test through "django" logger - Enter into the main()
2022-07-24 16:38:23,151 - ERROR - main - CustomHandler test through "django" logger - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 77, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 16:39:07,527 - CRITICAL - main - CustomHandler test through "django" logger - Enter into the new_function()
NoneType: None
2022-07-24 16:39:07,529 - CRITICAL - main - CustomHandler test through "django" logger - Enter into the main()
2022-07-24 16:39:07,531 - CRITICAL - main - CustomHandler test through "django" logger - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 77, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 16:39:29,806 - WARNING - main - CustomHandler test through "django" logger - Enter into the new_function()
NoneType: None
2022-07-24 16:39:29,808 - WARNING - main - CustomHandler test through "django" logger - Enter into the main()
2022-07-24 16:39:29,809 - WARNING - main - CustomHandler test through "django" logger - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 77, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 16:39:49,609 - INFO - main - CustomHandler test through "django" logger - Enter into the new_function()
NoneType: None
2022-07-24 16:39:49,610 - INFO - main - CustomHandler test through "django" logger - Enter into the main()
2022-07-24 16:39:49,612 - INFO - main - CustomHandler test through "django" logger - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 77, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 16:46:43,560 - ERROR - main - CustomHandler test through "django" logger - Enter into the new_function()
NoneType: None
2022-07-24 16:46:43,562 - ERROR - main - CustomHandler test through "django" logger - Enter into the main()
2022-07-24 16:46:43,564 - ERROR - main - CustomHandler test through "django" logger - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 77, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
2022-07-24 16:47:37,150 - ERROR - main - CustomHandler test through "django" logger - Enter into the new_function()
NoneType: None
2022-07-24 16:47:37,152 - ERROR - main - CustomHandler test through "django" logger - Enter into the main()
2022-07-24 16:47:37,154 - ERROR - main - CustomHandler test through "django" logger - Exception here, problem with item = 33
Traceback (most recent call last):
  File "c:/Users/admin/VisualStudion Folder/TEST-NEWSPORTAL-noM2M/NewsPortal/logging/main.py", line 77, in function
    print(item.split(' '))
AttributeError: 'int' object has no attribute 'split'
